# Generated by Django 4.1.2 on 2022-11-01 15:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuario', '0002_panel_cliente_modificado'),
    ]

    operations = [
        migrations.AlterField(
            model_name='panel_cliente',
            name='direccion',
            field=models.CharField(max_length=100),
        ),
    ]
